/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baitaplaptrinh3;

/**
 *
 * @author HUY
 */
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class FDesFile extends javax.swing.JFrame {

    /**
     * Creates new form FDesFile
     */
    private static final String netbeansPath ="C:";
    final JFileChooser fChooser;
    Des des;
    public FDesFile() {
        initComponents();
        fChooser = new JFileChooser(netbeansPath);
        des = new Des();
        
       
    }
 private void encryptFile() {
        File file = openFile();
        if (file != null) {
            byte[] fileByte = FileR.readFile(file);

            String key = txt_Key.getText();
            byte[] encFileByte = des.encryptFile(fileByte, key);
            displayGuiMessage("File " + file.getName() + " encrypted.", "Done", JOptionPane.INFORMATION_MESSAGE);
            File encFile = saveFile();
            Path path = encFile.toPath();
            try {
                Files.write(path, encFileByte);
            } catch (IOException e) {
            }
        }
    }

    //Open file to dec, decrypts and save decrypted file
    private void decryptFile() {
        File file = openFile();
        if (file != null) {
            byte[] fileByte = FileR.readFile(file);

            String key =txt_Key.getText();
            byte[] decFileByte = des.decryptFile(fileByte, key);
            displayGuiMessage("File " + file.getName() + " decrypted.", "Done", JOptionPane.INFORMATION_MESSAGE);
            File encFile = saveFile();
            Path path = encFile.toPath();
            try {
                Files.write(path, decFileByte);
            } catch (IOException e) {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_EncryptFile = new javax.swing.JButton();
        btn_DecryptFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Key = new javax.swing.JTextField();
        btn_Key = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_EncryptFile.setText("Encrypt File");
        btn_EncryptFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EncryptFileActionPerformed(evt);
            }
        });

        btn_DecryptFile.setText("Decrypt File");
        btn_DecryptFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DecryptFileActionPerformed(evt);
            }
        });

        jLabel1.setText("Key");

        btn_Key.setText("Generate Key");
        btn_Key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_EncryptFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_DecryptFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(txt_Key)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_Key, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 491, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_EncryptFile)
                .addGap(37, 37, 37)
                .addComponent(btn_DecryptFile)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btn_Key)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EncryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EncryptFileActionPerformed
        // TODO add your handling code here:
      encryptFile();
    }//GEN-LAST:event_btn_EncryptFileActionPerformed

    private void btn_DecryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DecryptFileActionPerformed
        // TODO add your handling code here:
      decryptFile();
    }//GEN-LAST:event_btn_DecryptFileActionPerformed

    private void btn_KeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KeyActionPerformed
        // TODO add your handling code here:
          String genKey = des.generateKey(16);
          txt_Key.setText(genKey);
    }//GEN-LAST:event_btn_KeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDesFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDesFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDesFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDesFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FDesFile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DecryptFile;
    private javax.swing.JButton btn_EncryptFile;
    private javax.swing.JButton btn_Key;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_Key;
    // End of variables declaration//GEN-END:variables

    

    private File openFile() {
        int openState = fChooser.showOpenDialog(this);

        if (openState == JFileChooser.APPROVE_OPTION) {
            return fChooser.getSelectedFile();
        } else {
            return null;
        }
    }

    private File saveFile() {
        int saveState = fChooser.showSaveDialog(this);

        if (saveState == JFileChooser.APPROVE_OPTION) {
            return fChooser.getSelectedFile();
        } else {
            return null;
        }
    }

    private void displayGuiMessage(String message, String windowTitle, int JOptionPaneMessType) {
        JOptionPane.showMessageDialog(this, message, windowTitle, JOptionPaneMessType);
    }
}
